### ISSUE TITLE
Spell Interrupted / GearSwap Issues

### ISSUE THREAD

**Issue by jcv-** [DiscipleOfEris/FastFollow#1]
When FastFollow is enabled and character is casting a spell, I receive the message that "the spell is interrupted" and as a result appears to be causing an issue with GearSwap midcast sets. The original spell goes through just fine, but it looks like FastFollow is attempting to cast something else during that time.

**Comment by Spliffmonkey187** [comment]
Been having the same issue (GearSwap-wise). I have found that FastFollow makes GearSwap lag especially when my Gearswap needs to say equip a magic burst set real fast(this is the scenario I have been able to replicate the problem in).

**Comment by jcv-** [comment]
@Spliffmonkey187 This is the work around that I have been using since I posted the original issue. This should go inside the init.txt file in Windower\Scripts\

// configure fastfollow
ffo pauseon any
ffo pausedelay 0

**Comment by Spliffmonkey187** [comment]
Hey there jcv, thanks for the reply, I will do that immediately and give it another test tonight. Will give some feedback

**Comment by anthem127** [comment]
Just ran into the gearswap timing issue as well, the work around is... working :)

**Comment by chrisellis111** [comment]
Fastfollow is killing the duration of my bard songs when its loaded. It seems likes its somehow trying to change into me idle set to early. has anyone seen this?

the below fix didn't work
// configure fastfollow
ffo pauseon any
ffo pausedelay 0

**Comment by damasterdr** [comment]
I'm having same issues.  Tried the suggest work around by JCV but was unsuccessful.  Any advice will be appreciate on fixing this issues. Thank you.

**Comment by damasterdr** [comment]
nevermind i figured it out by changing the pausedelay to 0 under the Fastfollow.lua file as a default.  Ty for the information it helped get to the root of the problems.

**Comment by ianandersonlol** [comment]
this has been fixed in the most recent version of fast follow.

```lua
// configure fastfollow
ffo pauseon any
ffo pausedelay 0

```
is no longer needed(and might break it now)

**Comment by ghost** [comment]
I'm on the latest release and still having this double casting issue. The previous solution suggested by other posters has solved the issue.
